### ISSUE TITLE
another NPE

### ISSUE THREAD

**Issue by micwin** [micwin/open-space#16]
looks like an avatar is missing or so

java.lang.NullPointerException
     at net.micwin.elysium.view.BasePage.ensureStoryShown(BasePage.java:220)
     at net.micwin.elysium.view.collective.NaniteGroupListPage.<init>(NaniteGroupListPage.java:71)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
     at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:177)
     at org.apache.wicket.session.DefaultPageFactory.newPage(DefaultPageFactory.java:68)

**Comment by micwin** [comment]
done. basepage was the problem
